#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

string generatePassword(int length) {
    const string charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-=[]{}|;:,.<>?";
    srand(time(0)); // Seed the random number generator with current time
    string password;
    for (int i = 0; i < length; ++i) {
        password += charset[rand() % charset.length()];
    }
    return password;
}

int main() {
    int passwordLength;
    cout << "Enter the length of the password you want to generate: ";
    cin >> passwordLength;

    if (passwordLength <= 0) {
        cerr << "Invalid password length. Please enter a positive integer." << endl;
        return 1; // Return non-zero exit status for error
    }

    string password = generatePassword(passwordLength);
    cout << "Generated Password: " << password << endl;

    return 0; // Return 0 for successful execution
}
}
